Improvement to entrypoint.sh
micronaut-projects/github-pages-deploy-action pull request #2
Opened 2020-12-12 05:09 UTC by puneetbehl

**Description**
This action does not work properly in the case of [grails/grom-hibernate5](https://github.com/grails/gorm-hibernate5) because there is already a docs folder in the project. So, with the flexibility to pass the name of the documentation folder we should be able to solve this problem.

In addition, I think we only need to clone gh-pages branch instead of cloning the whole repository.

2020-12-14 16:48 UTC, alvarosanchez commented
LGTM. @ilopmar what do you think?

2020-12-14 16:48 UTC, alvarosanchez approved these changes

2020-12-14 16:51 UTC, ilopmar commented
Not really sure. @alvarosanchez remember that last Friday we did this https://github.com/micronaut-projects/github-pages-deploy-action/commit/dacdbe3ad58bcd45231f291f5d23e13b1929370f because we are always cloning the repo in a new directory. If we don't clone it anymore I'm not sure if we are going to break something.

2020-12-14 17:20 UTC, alvarosanchez commented
Hmm I'm unclear now. @puneetbehl I thought your change was to introduce an optional variable to make it configurable the clone directory. But upon a closer look, I see it does more than that. Maybe we can have a call tomorrow and discuss.

2020-12-14 17:20 UTC, alvarosanchez approved these changes

2020-12-14 17:21 UTC, alvarosanchez requested changes
Disapproving for now

2020-12-14 19:10 UTC, puneetbehl commented
Sure we can connect tomorrow, as mentioned above the other change is to only clone the gh-pages branch and if one does not exists we create a new gh-pages branch with the README.md and push it. 

Also, I am not sure about the context @ilopmar  mentioned.

2020-12-15 08:41 UTC, ilopmar commented
> (...) as mentioned above the other change is to only clone the gh-pages branch and if one does not exists we create a new gh-pages branch with the README.md and push it.

@puneetbehl The current code already does that. `BRANCH` parameter [is mandatory](https://github.com/micronaut-projects/github-pages-deploy-action/blob/1c3fdafaab5b07dff4ac47faac6c529cc41e12a8/entrypoint.sh#L11). Then, if it doesn't exist it is [created here](https://github.com/micronaut-projects/github-pages-deploy-action/blob/1c3fdafaab5b07dff4ac47faac6c529cc41e12a8/entrypoint.sh#L64-L76).

2020-12-15 11:21 UTC, closed without merging